# Generated by Django 2.2.1 on 2019-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.EmailField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.BigIntegerField()),
                ('date_deactived', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.EmailField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.BigIntegerField()),
                ('date_deactived', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.EmailField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.BigIntegerField()),
                ('date_deactived', models.BigIntegerField()),
            ],
        ),
    ]
