# Generated by Django 2.2.1 on 2019-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.DateTimeField(blank=True, null=True)),
                ('date_deactived', models.DateTimeField(blank=True, null=True)),
                ('form', models.FileField(blank=True, null=True, upload_to='form/')),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.DateTimeField(blank=True, null=True)),
                ('date_deactived', models.DateTimeField(blank=True, null=True)),
                ('manual', models.FileField(blank=True, null=True, upload_to='manual/')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('version', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('date_actived', models.DateTimeField(blank=True, null=True)),
                ('date_deactived', models.DateTimeField(blank=True, null=True)),
                ('procedure', models.FileField(blank=True, null=True, upload_to='prosedur/')),
            ],
        ),
    ]
