# Generated by Django 2.2.1 on 2019-07-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190711_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to='form/'),
        ),
        migrations.AddField(
            model_name='manual',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='manual/'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure',
            field=models.FileField(blank=True, null=True, upload_to='prosedur/'),
        ),
    ]
