# Generated by Django 2.2.1 on 2019-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190711_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='manual',
            name='code',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(max_length=150),
        ),
    ]
