# Generated by Django 2.2.1 on 2019-06-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
