# Generated by Django 2.2.1 on 2019-05-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
