# Generated by Django 2.2.1 on 2019-05-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190508_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='curriculum_vitae/'),
        ),
    ]
