# Generated by Django 2.2.1 on 2019-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190513_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='media/curriculum_vitae/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/'),
        ),
    ]
