# Generated by Django 2.2.1 on 2019-05-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('completed', models.IntegerField()),
                ('left', models.IntegerField()),
                ('created', models.BigIntegerField()),
                ('updated', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StepsForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
            ],
        ),
        migrations.AddField(
            model_name='steps',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
        migrations.CreateModel(
            name='FilesProcessCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_formulir_aplikasi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_kelengkapan_dokumen', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_kajian_aplikasi_sertifikasi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_penawaran', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_perjanjian', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_invoice', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_kuitansi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_notifikasi_tim_audit_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_notifikasi_tim_audit_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_rencana_audit_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_rencana_audit_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_audit_kecukupan', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_daftar_hadir_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_daftar_hadir_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_ketidaksesuaian_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_ketidaksesuaian_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_audit_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_audit_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_verifikasi_ketidaksesuaian_tahap_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_verifikasi_ketidaksesuaian_tahap_1', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_notifikasi_tim_audit_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_rencana_audit_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_daftar_hadir_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_lembar_periksa_audit_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_lembar_periksa_audit', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_ketidaksesuaian_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_audit_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_buku_harian_auditor_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_buku_harian_auditor', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_pemantauan_lapangan_personnel_sertifikasi_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_pemantauan_lapangan_personnel_sertifikasi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_verifikasi_ketidaksesuaian_tahap_2', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_keterangan_bebas_konflik_kepentingan_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_keterangan_bebas_konflik_kepentingan', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_notifikasi_tim_evaluasi_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_notifikasi_tim_evaluasi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_evaluasi_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_laporan_evaluasi', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_memo_dinas_hasil_suv', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_memo_dinas_penerbitan_sertifikat', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_form_verifikasi_sertifikat', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_draft_sertifikat', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_sertifikat', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('files_program_survailen', models.FileField(blank=True, null=True, upload_to='files_process/')),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Certifications')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Certifications')),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
                ('steps_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsForms')),
            ],
        ),
        migrations.AddField(
            model_name='certifications',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
    ]
