# Generated by Django 2.2.1 on 2019-05-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('completed', models.IntegerField()),
                ('left', models.IntegerField()),
                ('created', models.BigIntegerField()),
                ('updated', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Steps_Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
            ],
        ),
        migrations.AddField(
            model_name='steps',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
        migrations.CreateModel(
            name='Certifications_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Certifications')),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
                ('steps_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps_Forms')),
            ],
        ),
        migrations.AddField(
            model_name='certifications',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
    ]
