# Generated by Django 2.2.1 on 2019-08-01 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('completed', models.IntegerField(default=0)),
                ('left', models.IntegerField()),
                ('created', models.BigIntegerField()),
                ('updated', models.BigIntegerField()),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('is_survailen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StepsSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
            ],
        ),
        migrations.CreateModel(
            name='StepsForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.IntegerField(choices=[(0, 'Number'), (1, 'Text')], default=1)),
                ('name', models.CharField(max_length=150)),
                ('tooltip', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsSections')),
            ],
        ),
        migrations.AddField(
            model_name='steps',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
        migrations.CreateModel(
            name='OfflineDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tooltip', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsSections')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('validator_role', models.IntegerField(default=0)),
                ('validator', models.IntegerField(blank=True, default=None, null=True)),
                ('validation_date', models.BigIntegerField(blank=True, default=None, null=True)),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Certifications')),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Steps')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsOfflineDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_path', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('certifications_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.CertificationsSteps')),
                ('offline_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.OfflineDocuments')),
                ('steps_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsSections')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('certifications_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.CertificationsSteps')),
                ('steps_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsForms')),
                ('steps_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.StepsSections')),
            ],
        ),
        migrations.AddField(
            model_name='certifications',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Types'),
        ),
    ]
