# Generated by Django 2.2.1 on 2019-05-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesProcessCertifications',
        ),
    ]
